INSERT INTO operationDeveloper (
  html_url,
  avatar_url,
  login,
  name,
  bio,
  company,
  location,
  email,
  twitter_username,
  followers,
  following,
  public_repos,
  total_stars,
  popular_repo,
  created_at,
  updated_at,
  ecosystems,
  sectors,
  createdAt,
  updatedAt
) VALUES (
      'https://github.com/laanwj',
      'https://avatars.githubusercontent.com/u/126646\\\?v=4',
      'laanwj',
      NULL,
      NULL,
      NULL,
      'The Netherlands',
      NULL,
      NULL,
      '4134',
      '6',
      '96',
      '1158',
      '{"html_url":"https://github.com/laanwj/nips","name":"nips","description":"laanwj fork","languages":[]}',
      '2009-09-14T08:32:17Z',
      '2024-12-07T15:32:45Z',
      '["BTC"]',
      '[]',
      NOW(),
      NOW()),
('https://github.com/luke-jr',
      'https://avatars.githubusercontent.com/u/1095675\\\?v=4',
      'luke-jr',
      'Luke Dashjr',
      NULL,
      NULL,
      NULL,
      'luke+github_public@dashjr.org',
      'lukedashjr',
      '2327',
      '0',
      '85',
      '2371',
      '{"html_url":"https://github.com/luke-jr/datum_gateway","name":"datum_gateway","description":"Decentralized Alternative Templates for Universal Mining","languages":[{"name":"C","percentage":96},{"name":"CMake","percentage":2},{"name":"HTML","percentage":2}]}',
      '2011-10-01T23:08:57Z',
      '2024-12-23T07:02:36Z',
      '["BTC"]',
      '[]',
      NOW(),
      NOW()),
('https://github.com/AmazingAng',
      'https://avatars.githubusercontent.com/u/14728591\\\?v=4',
      'AmazingAng',
      '0xAA',
      'Phd Candidate in Neuroscience,\\r\\nindependent educator in Web3.',
      'Peking University',
      'Beijing',
      'd0u.gie@hotmail.com',
      '0xAA_Science',
      '1889',
      '19',
      '43',
      '12634',
      '{"html_url":"https://github.com/AmazingAng/generative_agents","name":"generative_agents","description":"Generative Agents: Interactive Simulacra of Human Behavior","languages":[{"name":"Python","percentage":60},{"name":"HTML","percentage":40},{"name":"CSS","percentage":0}]}',
      '2015-09-22T06:53:49Z',
      '2024-12-19T12:28:13Z',
      '["EVM"]',
      '[]',
      NOW(),
      NOW()),
('https://github.com/sipa',
      'https://avatars.githubusercontent.com/u/548488\\\?v=4',
      'sipa',
      'Pieter Wuille',
      '@Bitcoin developer at @chaincodelabs. Formerly @Blockstream.',
      '@chaincodelabs',
      NULL,
      'pieter@wuille.net',
      'pwuille',
      '0',
      '0',
      '49',
      '1824',
      '{"html_url":"https://github.com/sipa/bitcoincore.org","name":"bitcoincore.org","description":"Bitcoin Core project website","languages":[{"name":"HTML","percentage":98},{"name":"SCSS","percentage":2},{"name":"Python","percentage":0}]}',
      '2011-01-05T11:11:02Z',
      '2024-12-15T02:45:18Z',
      '["BTC"]',
      '[]',