INSERT INTO operationDeveloper (
  html_url,
  avatar_url,
  login,
  name,
  bio,
  company,
  location,
  email,
  twitter_username,
  followers,
  following,
  public_repos,
  total_stars,
  popular_repo,
  created_at,
  updated_at,
  ecosystems,
  sectors,
  createdAt,
  updatedAt
) VALUES (
      'https://github.com/luke-jr',
      'https://avatars.githubusercontent.com/u/1095675\?v=4',
      'luke-jr',
      'Luke Dashjr',
      NULL,
      NULL,
      NULL,
      'luke+github_public@dashjr.org',
      'lukedashjr',
      '2328',
      '0',
      '85',
      '2370',
      '{"html_url":"https://github.com/luke-jr/datum_gateway","name":"datum_gateway","description":"Decentralized Alternative Templates for Universal Mining","languages":[{"name":"C","percentage":96},{"name":"CMake","percentage":2},{"name":"HTML","percentage":2}]}',
      '2011-10-01T23:08:57Z',
      '2024-12-23T07:02:36Z',
      '["Bitcoin"]',
      '[]',
      NOW(),
      NOW()),
('https://github.com/laanwj',
      'https://avatars.githubusercontent.com/u/126646\?v=4',
      'laanwj',
      NULL,
      NULL,
      NULL,
      'The Netherlands',
      NULL,
      NULL,
      '4129',
      '6',
      '96',
      '1157',
      '{"html_url":"https://github.com/laanwj/nips","name":"nips","description":"laanwj fork","languages":[]}',
      '2009-09-14T08:32:17Z',
      '2024-12-07T15:32:45Z',
      '["Bitcoin"]',
      '[]',
      NOW(),
      NOW()),
('https://github.com/sipa',
      'https://avatars.githubusercontent.com/u/548488\?v=4',
      'sipa',
      'Pieter Wuille',
      '@Bitcoin developer at @chaincodelabs. Formerly @Blockstream.',
      '@chaincodelabs',
      NULL,
      'pieter@wuille.net',
      'pwuille',
      '0',
      '0',
      '49',
      '1822',
      '{"html_url":"https://github.com/sipa/bitcoincore.org","name":"bitcoincore.org","description":"Bitcoin Core project website","languages":[{"name":"HTML","percentage":98},{"name":"SCSS","percentage":2},{"name":"Python","percentage":0}]}',
      '2011-01-05T11:11:02Z',
      '2024-12-15T02:45:18Z',
      '["Bitcoin"]',
      '[]',
      NOW(),
      NOW()),
('https://github.com/theuni',
      'https://avatars.githubusercontent.com/u/417043\?v=4',
      'theuni',
      'Cory Fields',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      '1088',
      '1',
      '62',
      '101',
      '{"html_url":"https://github.com/theuni/HiGHS","name":"HiGHS","description":"Linear optimization software","languages":[{"name":"C++","percentage":83},{"name":"C","percentage":10},{"name":"Python","percentage":3}]}',
      '2010-09-27T03:18:12Z',
      '2024-10-31T13:26:35Z',
      '["Bitcoin"]',
      '[]',