
INSERT INTO operationDeveloper (
  html_url,
  avatar_url,
  login,
  name,
  bio,
  company,
  location,
  email,
  twitter_username,
  followers,
  following,
  public_repos,
  total_stars,
  popular_repo,
  created_at,
  updated_at,
  ecosystems,
  sectors,
  createdAt,
  updatedAt
) VALUES 
(
      'https://github.com/apps/dependabot',
      'https://avatars.githubusercontent.com/in/29110\?v=4',
      'dependabot[bot]',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      0,
      0,
      0,
      0,
      NULL,
      '2019-04-16T22:34:25Z',
      '2019-05-23T08:22:16Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/rigelrozanski',
      'https://avatars.githubusercontent.com/u/20132176\?v=4',
      'rigelrozanski',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      137,
      98,
      26,
      20,
      '{"html_url":"https://github.com/rigelrozanski/tendermint","name":"tendermint","description":"⟁ Tendermint Core (BFT Consensus) in Go","languages":[{"name":"Go","percentage":85},{"name":"TeX","percentage":7},{"name":"TLA","percentage":6}]}',
      '2016-06-24T18:43:59Z',
      '2024-09-12T17:18:50Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/julienrbrt',
      'https://avatars.githubusercontent.com/u/29894366\?v=4',
      'julienrbrt',
      'Julien Robert',
      NULL,
      '@cosmos | @01builders | @ignite',
      'Netherlands',
      NULL,
      '_julienrbrt',
      167,
      61,
      22,
      7,
      '{"html_url":"https://github.com/julienrbrt/ibc-go","name":"ibc-go","description":"Inter-Blockchain Communication Protocol (IBC) implementation in Golang.","languages":[{"name":"Go","percentage":95},{"name":"TLA","percentage":4},{"name":"Python","percentage":0}]}',
      '2017-07-04T14:01:18Z',
      '2024-12-28T20:37:00Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/cwgoes',
      'https://avatars.githubusercontent.com/u/24760279\?v=4',
      'cwgoes',
      'Christopher Goes',
      NULL,
      NULL,
      'γαλαξίας κύκλος',
      NULL,
      'cwgoes',
      264,
      199,
      24,
      55,
      '{"html_url":"https://github.com/cwgoes/slips","name":"slips","description":"SatoshiLabs Improvement Proposals","languages":[{"name":"Markdown","percentage":96},{"name":"Python","percentage":4},{"name":"Shell","percentage":0}]}',
      '2016-12-25T04:56:26Z',
      '2024-12-13T15:29:56Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/alexanderbez',
      'https://avatars.githubusercontent.com/u/5265989\?v=4',
      'alexanderbez',
      'Aleksandr Bezobchuk',
      'blockchain | distributed systems ✌️\r\n@cosmos',
      NULL,
      'Brooklyn, NY',
      NULL,
      'aleksb3z',
      399,
      74,
      59,
      82,
      '{"html_url":"https://github.com/alexanderbez/novestingyield","name":"novestingyield","description":"A simple example of how to extend the Cosmos SDK''s x/distribution module to prohibit withdrawal of rewards for vesting accounts.","languages":[{"name":"Go","percentage":100}]}',
      '2013-08-20T01:10:37Z',
      '2024-12-11T18:37:19Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/AdityaSripal',
      'https://avatars.githubusercontent.com/u/14364734\?v=4',
      'AdityaSripal',
      'Aditya',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      132,
      9,
      39,
      20,
      '{"html_url":"https://github.com/AdityaSripal/ibc-go","name":"ibc-go","description":"Inter-Blockchain Communication Protocol (IBC) implementation in Golang.","languages":[{"name":"Go","percentage":95},{"name":"TLA","percentage":4},{"name":"Makefile","percentage":0}]}',
      '2015-09-19T20:59:03Z',
      '2024-12-17T08:41:45Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/mpoke',
      'https://avatars.githubusercontent.com/u/21082339\?v=4',
      'mpoke',
      'Marius Poke',
      NULL,
      'Informal Systems',
      NULL,
      NULL,
      NULL,
      29,
      0,
      7,
      30,
      '{"html_url":"https://github.com/mpoke/forge-testing","name":"forge-testing","description":null,"languages":[]}',
      '2016-08-17T13:21:14Z',
      '2024-12-17T15:00:47Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/colin-axner',
      'https://avatars.githubusercontent.com/u/25233464\?v=4',
      'colin-axner',
      'colin axnér',
      NULL,
      NULL,
      'stockholm',
      NULL,
      NULL,
      66,
      24,
      11,
      6,
      '{"html_url":"https://github.com/colin-axner/wasmd","name":"wasmd","description":"Basic cosmos-sdk app with web assembly smart contracts","languages":[{"name":"Go","percentage":98},{"name":"Shell","percentage":1},{"name":"Makefile","percentage":1}]}',
      '2017-01-19T21:14:13Z',
      '2024-12-29T20:36:43Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/sangier',
      'https://avatars.githubusercontent.com/u/45793271\?v=4',
      'sangier',
      NULL,
      NULL,
      NULL,
      'Madrid ',
      NULL,
      NULL,
      1,
      1,
      6,
      1,
      '{"html_url":"https://github.com/sangier/cw-ibc-lite","name":"cw-ibc-lite","description":"This is a WIP implementation of the ibc-lite specs purely in CosmWasm. It can communicate over IBC without using `ibc-go`.","languages":[{"name":"Go","percentage":51},{"name":"Rust","percentage":49},{"name":"Just","percentage":0}]}',
      '2018-12-11T14:30:24Z',
      '2024-09-25T08:13:49Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/webmaster128',
      'https://avatars.githubusercontent.com/u/2603011\?v=4',
      'webmaster128',
      'Simon Warta',
      'Building CosmWasm at Confio',
      '@confio',
      'localhost',
      NULL,
      'simon_warta',
      482,
      14,
      152,
      56,
      '{"html_url":"https://github.com/webmaster128/sink","name":"sink","description":"The sink contract","languages":[{"name":"Rust","percentage":87},{"name":"Shell","percentage":13}]}',
      '2012-10-19T22:47:29Z',
      '2024-12-20T12:27:39Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/willclarktech',
      'https://avatars.githubusercontent.com/u/11036220\?v=4',
      'willclarktech',
      'Will Clark',
      NULL,
      NULL,
      'Berlin, Germany',
      NULL,
      NULL,
      67,
      11,
      87,
      53,
      '{"html_url":"https://github.com/willclarktech/ai-interpretability","name":"ai-interpretability","description":null,"languages":[{"name":"Jupyter Notebook","percentage":100},{"name":"Shell","percentage":0},{"name":"Python","percentage":0}]}',
      '2015-02-16T22:09:14Z',
      '2024-12-14T14:23:17Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/ethanfrey',
      'https://avatars.githubusercontent.com/u/5689864\?v=4',
      'ethanfrey',
      'Ethan Frey',
      NULL,
      NULL,
      'Berlin, Germany',
      NULL,
      NULL,
      493,
      11,
      62,
      60,
      '{"html_url":"https://github.com/ethanfrey/vectis-extension-client","name":"vectis-extension-client","description":null,"languages":[{"name":"TypeScript","percentage":100}]}',
      '2013-10-15T09:30:08Z',
      '2024-12-21T15:06:02Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/msteiner96',
      'https://avatars.githubusercontent.com/u/69144826\?v=4',
      'msteiner96',
      'Milan Steiner',
      'Full Stack Developer',
      'MoonBite GmbH',
      'Heilbronn, Germany',
      NULL,
      'milan_cosmos',
      54,
      3,
      18,
      2,
      '{"html_url":"https://github.com/msteiner96/sorosplits","name":"sorosplits","description":"Sorosplits is a set of smart contracts & interfaces to enable split transactions and revenue sharing across multiple parties in the Stellar ecosystem.","languages":[{"name":"TypeScript","percentage":71},{"name":"Rust","percentage":27},{"name":"Shell","percentage":1}]}',
      '2020-08-03T09:27:10Z',
      '2024-12-19T05:20:55Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/apps/mergify',
      'https://avatars.githubusercontent.com/in/10562\?v=4',
      'mergify[bot]',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      0,
      0,
      0,
      0,
      NULL,
      '2018-03-30T10:19:51Z',
      '2018-04-18T12:01:25Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/okwme',
      'https://avatars.githubusercontent.com/u/964052\?v=4',
      'okwme',
      'billy rennekamp',
      NULL,
      '@trifle-labs, @clovers-network & @folia-app prev @cosmos & @interchainio',
      'Berlin',
      'billy.rennekamp@gmail.com',
      'billyrennekamp',
      478,
      285,
      149,
      76,
      '{"html_url":"https://github.com/okwme/ec-elgamal-circom","name":"ec-elgamal-circom","description":"ElGamal encryption/decryption Circom2 circuits on the Baby Jubjub curve with TypeScript integration for input handling, testing, and benchmarking.","languages":[{"name":"TypeScript","percentage":84},{"name":"Circom","percentage":9},{"name":"Shell","percentage":7}]}',
      '2011-08-07T05:56:16Z',
      '2024-12-22T16:47:27Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/tac0turtle',
      'https://avatars.githubusercontent.com/u/24299864\?v=4',
      'tac0turtle',
      'Marko',
      NULL,
      NULL,
      'E',
      NULL,
      NULL,
      313,
      13,
      60,
      26,
      '{"html_url":"https://github.com/tac0turtle/rawraw","name":"rawraw","description":null,"languages":[{"name":"Rust","percentage":100}]}',
      '2016-12-01T17:01:13Z',
      '2024-12-24T16:05:00Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/toschdev',
      'https://avatars.githubusercontent.com/u/8368497\?v=4',
      'toschdev',
      'Tobias',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      103,
      37,
      23,
      8,
      '{"html_url":"https://github.com/toschdev/chainlist","name":"chainlist","description":"📚 Chain Resource Managed By Cosmostation","languages":[{"name":"JavaScript","percentage":100}]}',
      '2014-08-05T23:51:43Z',
      '2024-12-19T16:08:56Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/jackzampolin',
      'https://avatars.githubusercontent.com/u/7452680\?v=4',
      'jackzampolin',
      'Jack Zampolin',
      NULL,
      '@peggyjv',
      'CA, USA',
      NULL,
      'jackzampolin',
      404,
      38,
      124,
      126,
      '{"html_url":"https://github.com/jackzampolin/rollchain","name":"rollchain","description":null,"languages":[]}',
      '2014-04-30T18:50:24Z',
      '2024-12-09T18:53:33Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/EmelyanenkoK',
      'https://avatars.githubusercontent.com/u/2539335\?v=4',
      'EmelyanenkoK',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      713,
      0,
      65,
      395,
      '{"html_url":"https://github.com/EmelyanenkoK/multisig-dapp","name":"multisig-dapp","description":null,"languages":[{"name":"TypeScript","percentage":91},{"name":"CSS","percentage":4},{"name":"HTML","percentage":4}]}',
      '2012-10-11T19:13:57Z',
      '2024-11-11T13:39:55Z',
      '["Ton"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/SpyCheese',
      'https://avatars.githubusercontent.com/u/11584995\?v=4',
      'SpyCheese',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      130,
      0,
      15,
      52,
      '{"html_url":"https://github.com/SpyCheese/validator-bench","name":"validator-bench","description":null,"languages":[{"name":"Python","percentage":100}]}',
      '2015-03-21T12:20:00Z',
      '2024-12-17T11:16:48Z',
      '["Ton"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/neodix42',
      'https://avatars.githubusercontent.com/u/52255577\?v=4',
      'neodix42',
      NULL,
      NULL,
      NULL,
      NULL,
      'neodiX@ton.org',
      NULL,
      162,
      3,
      31,
      264,
      '{"html_url":"https://github.com/neodix42/ton-http-api","name":"ton-http-api","description":"HTTP API for TON (The Open Network)","languages":[{"name":"Python","percentage":96},{"name":"Shell","percentage":4},{"name":"Dockerfile","percentage":1}]}',
      '2019-06-26T17:51:53Z',
      '2024-12-25T08:07:17Z',
      '["Ton"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/dungeon-master-666',
      'https://avatars.githubusercontent.com/u/98183742\?v=4',
      'dungeon-master-666',
      'Marat',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      88,
      2,
      6,
      20,
      '{"html_url":"https://github.com/dungeon-master-666/mytonctrl","name":"mytonctrl","description":"A tool to run and maintain a TON node/validator","languages":[{"name":"Python","percentage":93},{"name":"Shell","percentage":7}]}',
      '2022-01-21T18:40:46Z',
      '2024-11-18T22:30:25Z',
      '["Ton"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/tolya-yanot',
      'https://avatars.githubusercontent.com/u/1449561\?v=4',
      'tolya-yanot',
      'Tolya',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      742,
      0,
      2,
      74,
      '{"html_url":"https://github.com/tolya-yanot/w5","name":"w5","description":"Experimental wallet v5","languages":[{"name":"TypeScript","percentage":98},{"name":"JavaScript","percentage":1},{"name":"Shell","percentage":1}]}',
      '2012-02-18T17:03:24Z',
      '2024-12-30T14:58:58Z',
      '["Ton"]',
      '[]',
      NOW(),
      NOW()
    )
ON DUPLICATE KEY UPDATE
  avatar_url = VALUES(avatar_url),
  name = VALUES(name),
  bio = VALUES(bio),
  company = VALUES(company),
  location = VALUES(location),
  email = VALUES(email),
  twitter_username = VALUES(twitter_username),
  followers = VALUES(followers),
  following = VALUES(following),
  public_repos = VALUES(public_repos),
  total_stars = VALUES(total_stars),
  popular_repo = VALUES(popular_repo),
  updated_at = VALUES(updated_at),
  ecosystems = JSON_MERGE_PRESERVE(ecosystems, VALUES(ecosystems)),
  updatedAt = NOW();
