INSERT INTO operationDeveloper (
  html_url,
  avatar_url,
  login,
  name,
  bio,
  company,
  location,
  email,
  twitter_username,
  followers,
  following,
  public_repos,
  total_stars,
  popular_repo,
  created_at,
  updated_at,
  ecosystems,
  sectors,
  createdAt,
  updatedAt
) VALUES 
(
      'https://github.com/obscuren',
      'https://avatars.githubusercontent.com/u/6264126?v=4',
      'obscuren',
      'Jeffrey Wilcke',
      'Video Game Developer, Founder of @Grid-Games and @ethereum & Gopher',
      'Grid Games',
      'Amsterdam, NL',
      'jeff@grid-games.com',
      NULL,
      1715,
      1,
      50,
      349,
      '{"html_url":"https://github.com/obscuren/obscuren.github.io","name":"obscuren.github.io","description":null,"languages":[]}',
      '2013-12-26T10:54:54Z',
      '2024-11-20T13:50:12Z',
      '["Blockchain"]',
      '[]',
      NOW(),
      NOW()
),
(
      'https://github.com/msimovic',
      'https://avatars.githubusercontent.com/u/1518898?v=4',
      'msimovic',
      'Marko Simovic',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      5,
      0,
      2,
      2,
      '{"html_url":"https://github.com/msimovic/cpp-ethereum","name":"cpp-ethereum","description":"Gavin Wood''s C++ implementation of the Ethereum whitepaper.","languages":[{"name":"C++","percentage":67},{"name":"C","percentage":31},{"name":"Assembly","percentage":2}]}',
      '2012-03-09T05:25:04Z',
      '2024-10-24T18:12:16Z',
      '["Blockchain"]',
      '[]',
      NOW(),
      NOW()
),
(
      'https://github.com/CJentzsch',
      'https://avatars.githubusercontent.com/u/8452011?v=4',
      'CJentzsch',
      'Christoph Jentzsch',
      'Theoretical physicist |\nEthereum Foundation Alumni |\nslock.it co-founder |\ncorpus.ventures co-founder',
      'CEO corpus.ventures',
      'Deutschland',
      'jentzsch.software@gmail.com',
      'ChrJentzsch',
      311,
      5,
      25,
      4,
      '{"html_url":"https://github.com/CJentzsch/startup-finance","name":"startup-finance","description":"Open Source Client Side Captable Worksheet","languages":[{"name":"TypeScript","percentage":97},{"name":"JavaScript","percentage":2},{"name":"CSS","percentage":1}]}',
      '2014-08-14T19:48:54Z',
      '2024-11-18T17:21:11Z',
      '["Blockchain"]',
      '[]',
      NOW(),
      NOW()
),
(
      'https://github.com/karalabe',
      'https://avatars.githubusercontent.com/u/129561?v=4',
      'karalabe',
      'Péter Szilágyi',
      'Team lead at @ethereum',
      '@ethereum',
      NULL,
      'peterke@gmail.com',
      NULL,
      2849,
      0,
      40,
      3495,
      '{"html_url":"https://github.com/karalabe/runme","name":"runme","description":"Execute a GitHub repo","languages":[{"name":"Makefile","percentage":54},{"name":"Shell","percentage":43},{"name":"Go","percentage":2}]}',
      '2009-09-21T15:01:01Z',
      '2024-09-20T13:43:24Z',
      '["Blockchain"]',
      '[]',
      NOW(),
      NOW()
),
(
      'https://github.com/vbuterin',
      'https://avatars.githubusercontent.com/u/2230894?v=4',
      'vbuterin',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      12491,
      1,
      59,
      3048,
      '{"html_url":"https://github.com/vbuterin/Pyramid-Flow","name":"Pyramid-Flow","description":"Code of Pyramidal Flow Matching for Efficient Video Generative Modeling","languages":[{"name":"Python","percentage":95},{"name":"Jupyter Notebook","percentage":3},{"name":"Shell","percentage":2}]}',
      '2012-08-28T00:33:09Z',
      '2024-12-27T13:13:08Z',
      '["DeFi"]',
      '[]',
      NOW(),
      NOW()
),
(
      'https://github.com/zelig',
      'https://avatars.githubusercontent.com/u/374934?v=4',
      'zelig',
      'Viktor Trón',
      'free dom fighter, code artist\n\nfounder and architect of Swarm.\n\n@Ethereum OG, ex project lead at EF\n\n@ethersphere founder',
      'swarm, ethersphere, ethereum',
      'ethersphere',
      'viktor.tron@gmail.com',
      'zeligf',
      276,
      1,
      25,
      7,
      '{"html_url":"https://github.com/zelig/specs-andi","name":"specs-andi","description":null,"languages":[{"name":"TeX","percentage":100}]}',
      '2011-05-05T09:44:13Z',
      '2024-08-24T05:00:40Z',
      '["Blockchain"]',
      '[]',
      NOW(),
      NOW()
),
(
      'https://github.com/frozeman',
      'https://avatars.githubusercontent.com/u/232662?v=4',
      'frozeman',
      'Fabian Vogelsteller',
      'LUKSO Founder,\nEthereum developer, creator of the Mist browser, web3.js and ERC20. Author of a Meteor.js book and creator of the feindura - flat file CMS',
      'LUKSO',
      'Berlin, Germany',
      'fabian@lukso.network',
      'feindura',
      1877,
      8,
      117,
      719,
      '{"html_url":"https://github.com/frozeman/chains","name":"chains","description":"provides metadata for networkIDs and chainIDs","languages":[{"name":"Kotlin","percentage":94},{"name":"JavaScript","percentage":6}]}',
      '2010-03-29T15:09:24Z',
      '2024-12-16T12:39:31Z',
      '["Blockchain"]',
      '[]',
      NOW(),
      NOW()
)
ON DUPLICATE KEY UPDATE
  avatar_url = VALUES(avatar_url),
  name = VALUES(name),
  bio = VALUES(bio),
  company = VALUES(company),
  location = VALUES(location),
  email = VALUES(email),
  twitter_username = VALUES(twitter_username),
  followers = VALUES(followers),
  following = VALUES(following),
  public_repos = VALUES(public_repos),
  total_stars = VALUES(total_stars),
  popular_repo = VALUES(popular_repo),
  updated_at = VALUES(updated_at),
  ecosystems = JSON_MERGE_PRESERVE(ecosystems, VALUES(ecosystems)),
  updatedAt = NOW();
