
INSERT INTO operationProject (
  repoUrl,
  repoName,
  name,
  description,
  languages,
  stargazers_count,
  forks_count,
  topics,
  contributors,
  updated_at,
  created_at,
  ecosystems,
  sectors,
  createdAt,
  updatedAt
) VALUES 
(
      'https://github.com/cosmos/cosmos-sdk',
      'cosmos/cosmos-sdk',
      'cosmos-sdk',
      ':chains: A Framework for Building High Value Public Blockchains :sparkles:',
      '["Go"]',
      6373,
      3707,
      '["blockchain","cometbft","cosmos-sdk","cryptocurrency","go","golang","tendermint"]',
      '[{"login":"dependabot[bot]","avatar_url":"https://avatars.githubusercontent.com/in/29110?v=4"},{"login":"rigelrozanski","avatar_url":"https://avatars.githubusercontent.com/u/20132176?v=4"},{"login":"julienrbrt","avatar_url":"https://avatars.githubusercontent.com/u/29894366?v=4"},{"login":"cwgoes","avatar_url":"https://avatars.githubusercontent.com/u/24760279?v=4"},{"login":"alexanderbez","avatar_url":"https://avatars.githubusercontent.com/u/5265989?v=4"}]',
      '2024-12-30T14:59:07Z',
      '2024-12-30T17:58:46.098Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/cosmos/ibc',
      'cosmos/ibc',
      'ibc',
      'Interchain Standards (ICS) for the Cosmos network & interchain ecosystem.',
      '["TeX"]',
      944,
      395,
      '["blockchain","cosmos","distributed-ledger","interchain"]',
      '[{"login":"AdityaSripal","avatar_url":"https://avatars.githubusercontent.com/u/14364734?v=4"},{"login":"cwgoes","avatar_url":"https://avatars.githubusercontent.com/u/24760279?v=4"},{"login":"mpoke","avatar_url":"https://avatars.githubusercontent.com/u/21082339?v=4"},{"login":"colin-axner","avatar_url":"https://avatars.githubusercontent.com/u/25233464?v=4"},{"login":"sangier","avatar_url":"https://avatars.githubusercontent.com/u/45793271?v=4"}]',
      '2024-12-28T02:41:17Z',
      '2024-12-30T17:59:04.031Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/cosmos/cosmjs',
      'cosmos/cosmjs',
      'cosmjs',
      'The Swiss Army knife to power JavaScript based client solutions ranging from Web apps/explorers over browser extensions to server-side clients like faucets/scrapers.',
      '["TypeScript"]',
      657,
      346,
      '[]',
      '[{"login":"webmaster128","avatar_url":"https://avatars.githubusercontent.com/u/2603011?v=4"},{"login":"willclarktech","avatar_url":"https://avatars.githubusercontent.com/u/11036220?v=4"},{"login":"ethanfrey","avatar_url":"https://avatars.githubusercontent.com/u/5689864?v=4"},{"login":"msteiner96","avatar_url":"https://avatars.githubusercontent.com/u/69144826?v=4"},{"login":"mergify[bot]","avatar_url":"https://avatars.githubusercontent.com/in/10562?v=4"}]',
      '2024-12-30T00:18:43Z',
      '2024-12-30T17:59:22.374Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/cosmos/awesome-cosmos',
      'cosmos/awesome-cosmos',
      'awesome-cosmos',
      'Collection of Cosmos related resources',
      '[null]',
      545,
      157,
      '["awesome","awesome-list","blockchain","cosmos","cosmos-sdk"]',
      '[{"login":"okwme","avatar_url":"https://avatars.githubusercontent.com/u/964052?v=4"},{"login":"julienrbrt","avatar_url":"https://avatars.githubusercontent.com/u/29894366?v=4"},{"login":"tac0turtle","avatar_url":"https://avatars.githubusercontent.com/u/24299864?v=4"},{"login":"toschdev","avatar_url":"https://avatars.githubusercontent.com/u/8368497?v=4"},{"login":"jackzampolin","avatar_url":"https://avatars.githubusercontent.com/u/7452680?v=4"}]',
      '2024-12-26T18:33:07Z',
      '2024-12-30T17:59:41.765Z',
      '["Cosmos"]',
      '[]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/ton-blockchain/ton',
      'ton-blockchain/ton',
      'ton',
      'Main TON monorepo',
      '["C++"]',
      3153,
      1029,
      '["blockchain","cryptocurrency","infinite-sharding","ton"]',
      '[{"login":"EmelyanenkoK","avatar_url":"https://avatars.githubusercontent.com/u/2539335?v=4"},{"login":"SpyCheese","avatar_url":"https://avatars.githubusercontent.com/u/11584995?v=4"},{"login":"neodix42","avatar_url":"https://avatars.githubusercontent.com/u/52255577?v=4"},{"login":"dungeon-master-666","avatar_url":"https://avatars.githubusercontent.com/u/98183742?v=4"},{"login":"tolya-yanot","avatar_url":"https://avatars.githubusercontent.com/u/1449561?v=4"}]',
      '2024-12-30T10:26:43Z',
      '2024-12-30T17:59:59.751Z',
      '["Ton"]',
      '[]',
      NOW(),
      NOW()
    )
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  description = VALUES(description),
  languages = VALUES(languages),
  stargazers_count = VALUES(stargazers_count),
  forks_count = VALUES(forks_count),
  topics = VALUES(topics),
  contributors = VALUES(contributors),
  updated_at = VALUES(updated_at),
  ecosystems = JSON_MERGE_PRESERVE(ecosystems, VALUES(ecosystems)),
  updatedAt = NOW();
