
INSERT INTO operationDeveloper (
  html_url,
  avatar_url,
  login,
  name,
  bio,
  company,
  location,
  email,
  twitter_username,
  followers,
  following,
  public_repos,
  total_stars,
  popular_repo,
  created_at,
  updated_at,
  ecosystems,
  sectors,
  createdAt,
  updatedAt
) VALUES 
(
      'https://github.com/skia-flutter-autoroll',
      'https://avatars.githubusercontent.com/u/37626415?v=4',
      'skia-flutter-autoroll',
      NULL,
      NULL,
      NULL,
      NULL,
      'skia-flutter-autoroll@skia.org',
      NULL,
      39,
      0,
      1,
      0,
      NULL,
      '2018-03-21T14:22:40Z',
      '2022-08-26T17:33:03Z',
      '[]',
      '["AI"]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/engine-flutter-autoroll',
      'https://avatars.githubusercontent.com/u/42042535?v=4',
      'engine-flutter-autoroll',
      NULL,
      NULL,
      NULL,
      NULL,
      'engine-flutter-autoroll@skia.org',
      NULL,
      399,
      0,
      3,
      0,
      NULL,
      '2018-08-02T16:52:44Z',
      '2022-08-26T17:30:13Z',
      '[]',
      '["AI"]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/abarth',
      'https://avatars.githubusercontent.com/u/112007?v=4',
      'abarth',
      'Adam Barth',
      NULL,
      NULL,
      'San Francisco, CA',
      NULL,
      NULL,
      1488,
      0,
      55,
      0,
      NULL,
      '2009-08-05T02:32:48Z',
      '2024-11-20T15:43:39Z',
      '[]',
      '["AI"]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/jonahwilliams',
      'https://avatars.githubusercontent.com/u/8975114?v=4',
      'jonahwilliams',
      'Jonah Williams',
      'Rock, Flag, and Eagle',
      '@google ',
      'Mountain View, CA',
      'jonahwilliams@google.com',
      NULL,
      1809,
      39,
      144,
      0,
      NULL,
      '2014-09-30T17:45:54Z',
      '2024-11-29T08:39:24Z',
      '[]',
      '["AI"]',
      NOW(),
      NOW()
    ),
(
      'https://github.com/Hixie',
      'https://avatars.githubusercontent.com/u/551196?v=4',
      'Hixie',
      'Ian Hickson',
      NULL,
      NULL,
      NULL,
      'ian@hixie.ch',
      'Hixie',
      1758,
      0,
      84,
      0,
      NULL,
      '2011-01-07T00:32:46Z',
      '2024-12-31T01:28:45Z',
      '[]',
      '["AI"]',
      NOW(),
      NOW()
    )
ON DUPLICATE KEY UPDATE
  avatar_url = VALUES(avatar_url),
  name = VALUES(name),
  bio = VALUES(bio),
  company = VALUES(company),
  location = VALUES(location),
  email = VALUES(email),
  twitter_username = VALUES(twitter_username),
  followers = VALUES(followers),
  following = VALUES(following),
  public_repos = VALUES(public_repos),
  total_stars = VALUES(total_stars),
  popular_repo = VALUES(popular_repo),
  updated_at = VALUES(updated_at),
  ecosystems = JSON_ARRAY_APPEND(
    COALESCE(ecosystems, '[]'),
    '$',
    JSON_EXTRACT(VALUES(ecosystems), '$[0]')
  ),
  sectors = JSON_ARRAY_APPEND(
    COALESCE(sectors, '[]'),
    '$',
    JSON_EXTRACT(VALUES(sectors), '$[0]')
  ),
  updatedAt = NOW();
