name: Package-Info Action

description: Set package info vars to be used in other steps

inputs:
  module_name:
    required: true
  module_version:
    required: true

outputs:
  owner:
    value: ${{ steps.package_info.outputs.owner }}
    description: package owner
  name:
    value: ${{ steps.package_info.outputs.name }}
    description: package name
  version:
    value: ${{ steps.package_info.outputs.version }}
    description: package version

runs:
  using: composite
  steps:

    - id: package_info
      shell: bash
      run: |
        OWNER=$(echo ${{ github.repository }} | cut -d'/' -f1)
        NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
        MODULE_NAME=${{ inputs.module_name }}
        VERSION=${{ inputs.module_version}}

        echo "Package owner: $OWNER"
        echo "Repo name: $NAME"
        echo "Package name: $MODULE_NAME"
        echo "Package version: $VERSION"

        echo "::set-output name=owner::$OWNER"
        echo "::set-output name=name::$MODULE_NAME"
        echo "::set-output name=version::$VERSION"
