export const CONFIGS = {
  API_ENDPOINT: process.env.NEXT_PUBLIC_API_ENDPOINT ?? '',
  PROVIDER_INFURA_KEY: process.env.NEXT_PUBLIC_PROVIDER_INFURA_KEY ?? '',
  PROVIDER_ALCHEMY_KEY: process.env.NEXT_PUBLIC_PROVIDER_ALCHEMY_KEY ?? '',
  WALLETCONNECT_PROJECT_ID:
    process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID ?? '',
};
